version: '2'
services:
  postgres:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
  web:
    build: ./
    volumes:
      - ./:/home/docker/app
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 3333:3333
    working_dir: /home/docker/app
    command: bash -c "npm i && npm run serve:dev"