version: 2
jobs:
  build:
    docker:
      - image: postgres
        environment:
          POSTGRES_DB=root
          POSTGRES_PASSWORD=root
          POSTGRES_USER=root
      - image: circleci/node:7.10
        environment:
          PATH: "${PATH}:var/www/html/node_modules/.bin"
    working_directory: /var/www/html
    steps:
      - checkout
      - run: node -v
      - run: yarn --varsion
      - run: yarn install
      - run:
          name: Initialize Database
          command: |
            ./ace migration:refresh
            ./ace db:seed
      - run: npm run test
