version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: postgres
        environment:
          POSTGRES_DB=root
          POSTGRES_PASSWORD=root
          POSTGRES_USER=root
      - image: node:8.5.0
        environment:
          HOST=0.0.0.0
          NODE_ENV=development
          CACHE_VIEWS=false
          DB_CONNECTION=pg
          DB_HOST=localhost
          DB_PORT=5432
          DB_USER=root
          DB_PASSWORD=root
          DB_DATABASE=root

    working_directory: /var/www/html

    steps:
      - checkout
      - run: ls /var/www/html
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: node -v
      - run: yarn --varsion
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Initialize Database
          command: |
            /var/www/html/./ace migration:refresh
            /var/www/html/./ace db:seed
      # run tests!
      - run: yarn test


