version: 2
jobs:
  build:
    docker:
      - image: postgres
        environment:
          POSTGRES_DB=root
          POSTGRES_PASSWORD=root
          POSTGRES_USER=root
      - image: node:8.5.0
    working_directory: /var/www/html
    steps:
      - checkout
      - run: node -v
      - run: npm i -g npm@5.1.*
      - run: npm i
      - run:
          name: Initialize Database
          command: |
            ./ace migration:refresh
            ./ace db:seed
      - run: npm run test
